### ISSUE TITLE
Once a front-end rest client has been added to the app, the home page does not load

### ISSUE THREAD

**Issue by PierreBesson** [cbornet/generator-jhipster-swagger-cli#1]
I tried several times and keep encountering this issue. I'm using the latest master so that may be the reason.
I simply generated a new jhipster app and a swagger-cli client on the petstore. I'm using jhipster-swagger-cli version 0.4.0.

```
{
  "generator-jhipster": {
    "jhipsterVersion": "2.27.0",
    "baseName": "jhip",
    "packageName": "com.ippon.pierre",
    "packageFolder": "com/ippon/pierre",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "5100327d57c88bb37b25f6e3e84483337eb7d0c2",
    "useSass": false,
    "enableTranslation": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ]
  },
  "generator-jhipster-swagger-cli": {
    "apis": {
      "petstore": {
        "spec": "http://petstore.swagger.io/v2/swagger.json",
        "cliTypes": [
          "front"
        ]
      }
    }
  }
}

```

**Comment by cbornet** [comment]
From the look of your conf, you are using the master
The master has breaking changes so this module is not compatible anymore.
Can you try with the 2.27.0 RELEASE ?

**Comment by cbornet** [comment]
If you really want to use the master, I can make a branch and do the migration now

**Comment by PierreBesson** [comment]
You are right, retrying with the 2.27 release, the issue disappear. 
Yes, when you have time to work on it, it would be great to have a branch of your module that we could use on the master/next version.

**Comment by PierreBesson** [comment]
I guess you can close this issue now.

**Comment by cbornet** [comment]
WIP for JHipster 3. Shouldn't be long.

**Comment by cbornet** [comment]
@PierreBesson can you test with branch "jhipster3" ?
