### ISSUE TITLE
FeignClient is not using the JHipster Registry

### ISSUE THREAD

**Issue by agoncal** [cbornet/generator-jhipster-swagger-cli#10]
Let's say I have two microservices:

* [NumberAPI](https://github.com/agoncal/agoncal-talk-17msexperience/tree/master/demo03/number-api) has no DB, nothing, and just generates an ISBN number
* [BookAPI](https://github.com/agoncal/agoncal-talk-17msexperience/tree/master/demo03/book-api) does CRUD operations on a [Book entity](https://github.com/agoncal/agoncal-talk-17msexperience/blob/master/demo03/book-api/src/main/java/org/agoncal/talk/msexperience/demo03/bookapi/domain/Book.java). The book has a title, a price and an ISBN. The BookAPI invokes the Number API so it can get an ISBN number when [creating a Book](https://github.com/agoncal/agoncal-talk-17msexperience/blob/fe3e6e1195664c02aae009cc359f80ffcde24e75/demo03/book-api/src/main/java/org/agoncal/talk/msexperience/demo03/bookapi/web/rest/BookResource.java#L56)

In Book API I use the jhipster-swagger-cli to generate a [Java client](https://github.com/agoncal/agoncal-talk-17msexperience/tree/master/demo03/book-api/src/main/java/org/agoncal/talk/msexperience/demo03/bookapi/client) to invoke the Number API. The generated code for the FeignClient is : 

```
@FeignClient(name="${numberapi.name:numberapi}", url="${numberapi.url:https://localhost:8081}", configuration = ClientConfiguration.class)
public interface ApiApiClient extends ApiApi {
```

As you can see, the URL of Number API is hardcoded ([https://localhost:8081]()) and the `numberapi.url` variable being not set, it doesn't use the JHipster registry. Thanks to @jdubois I managed to get it work just by putting the registry name of the service:

```
@FeignClient(value = "numberapi")
public interface ApiApiClient extends ApiApi {
}
```

Shouldn't this be the default when doing microservices ? Is this the recommended way ? 

Thanks

**Comment by cbornet** [comment]
Can you try configuring in the application.yml
```yaml
numberapi.url: ""
```

**Comment by agoncal** [comment]
Yes it works... but I don't find that very intuitive. URL being empty now, it's difficult to understand that it goes to the registry. 

But if it's the way to go, maybe jhipster-swagger-cli could at least create the variable `numberapi.url` in the application.yml, assign it the default URL, and add some doc:

```
# Leave the URL empty if you want to leave the JHipster registry to solve it
numberapi.url: "https://localhost:8081"
```

WDYT ?

**Comment by cbornet** [comment]
Yes. The thing is : the module is meant to work with both JHipster microservices and external APIs. 
Maybe we could generate different code when the spec was generated from a registered micro-service (ie when `useRegistry` is true)

**Comment by agoncal** [comment]
In the `.yo_rc.json` you actually find two valuable informations : 

```
    "serviceDiscoveryType": "eureka",
    "applicationType": "microservice",
```

I know JHipster has a Consul support and some work has been done around Traeffik. Wonder if a Feign client can be used by those two.

Any way, one way of the other it would be great to have it working out of the box (with microservices and external APIs) ;o)

**Comment by cbornet** [comment]
> In the `.yo_rc.json` you actually find two valuable informations : 
    "serviceDiscoveryType": "eureka",
    "applicationType": "microservice",

Yes but your micro-service could call external APIs :smile: 
But I agree we can do better : if the client is generated using the registry, push a `useRegistry` tag to the template to generate different code.
Do you want to do it ?

**Comment by agoncal** [comment]
Lack of time and lack of knowledge on the code generation :o(

But I would love to implement it on a hackathon with a bit of help to start.

**Comment by cbornet** [comment]
Better late than never 😅

**Comment by agoncal** [comment]
@cbornet can't wait to give it a try ;o)
