### ISSUE TITLE
JWT auth not supported in backend?

### ISSUE THREAD

**Issue by harry-g** [cbornet/generator-jhipster-swagger-cli#12]
Sorry if I am misled, but could it be that JWT auth (the jHipster default) is not yet supported?
I found nothing about it so far, despite the test in travis subdir (which imho says "authentication failed" in last run of tests in travis logs).

**Comment by cbornet** [comment]
JWT auth doesn’t exist in swagger 2.0. You’ll need to add a Feign interceptor yourself.
Is your remote server another JHipster app ?

**Comment by harry-g** [comment]
Yes, its a Standard jHipster Server and I want to access it with a separate
Java Client... Maybe I'll move to Session based auth, as nothing is
productive yet...

Christophe Bornet <notifications@github.com> schrieb am Fr., 18. Mai 2018,
19:33:

**Comment by PierreBesson** [comment]
@harry_g I have added such a FeignInterceptor a few weeks ago in JHipster master so it should be working now in JHi 5 apps, have a look  at the genrated FeignConfiguration/FeignInterceptor classes. The only thing that you have to keep in mind is that your jwt secret should be the same for all apps. Typically you configure it in a central configuration server.

**Comment by harry-g** [comment]
Great news, thanks Pierre for the info!
Means, I just have to update to JHi5 and then try to regenerate the Feign
client, right?
Will try and let you know if it works...

2018-05-19 8:22 GMT+02:00 Pierre Besson <notifications@github.com>:

**Comment by cbornet** [comment]
This module will probably not work with JH5. I need to upgrade it.

**Comment by cbornet** [comment]
FYI the latest version of the module works with JH5

**Comment by cbornet** [comment]
Closing as old issue and module is now integrated in main gen.
