### ISSUE TITLE
Question: Would it be possible to replace call to the codegen jar with use of the maven/gradle-plugin ?

### ISSUE THREAD

**Issue by PierreBesson** [cbornet/generator-jhipster-swagger-cli#13]
This module is super cool but I'm sure more people would use if it was integrated in the JHipster cli itself. However the only thing preventing it is that this depends on openapi-generator.jar but what if we could rely on the openapigen maven/gradle plugin directly. @cbornet  Is it doable ?

**Comment by cbornet** [comment]
I guess it could be used. Originally I was reluctant due to the slow release rate of swagger-codegen. But with OpenAPI-generator it's different so I'll reconsider.

**Comment by cbornet** [comment]
About integrating in the main gen maybe we could have a vote for this ?

**Comment by ecostanzi** [comment]
Hi! Any news about the integration in the main generator? Are you still considering to replace the jar with maven/gradle plugin? I could give this a try

**Comment by PierreBesson** [comment]
Yes we are still considering it. We even discussed this together @cbornet and I when we met last week. However we don't have the time to work on this right now. If you are interested to do the integration yourself, you can open an issue on JHipster/generator-jhipster to request the feature.

**Comment by ecostanzi** [comment]
I found some time to look into it and opened this issue: https://github.com/jhipster/generator-jhipster/issues/9548

**Comment by cbornet** [comment]
@PierreBesson can be closed I guess ?

**Comment by PierreBesson** [comment]
Yes another solution has been found by using the npm release of openapigenerator-cli
