### ISSUE TITLE
Update for JH 3.7.1 AuthorizedFeignClient compatibility

### ISSUE THREAD

**Issue by brunnels** [cbornet/generator-jhipster-swagger-cli#8]
JH 3.7.1 added Spring Cloud Feign Client integration so it would be nice if this generator could support that.  It's not that difficult to do manually so hopefully not too difficult to add support in this generator.

Here's an example.

jhipster gateway with jhipster uaa microservice.

URL = http://localhost:8080/uaa/v2/api-docs
ApiClient Name = uaa

backend-client files should be generated like so

java/com/test/client/uaa/UaaApiClient.java
java/com/test/client/uaa/api/UaaApi.java
java/com/test/client/uaa/model/KeyAndPasswordVM.java
java/com/test/client/uaa/model/ManagedUserVM.java
java/com/test/client/uaa/model/ProfileInfoResponse.java
java/com/test/client/uaa/model/UserDTO.java

UaaApiClient.java

```
package com.test.client.uaa;

import com.test.client.AuthorizedFeignClient;
import com.test.client.uaa.api.UaaApi;

@AuthorizedFeignClient(name="${feignclient.uaa.service-name:uaa}")
public interface UaaApiClient extends UaaApi {
}
```

It would also be nice if you could specify the DateTime class to use in the generated model classes.  I have to do a search/replace to change to ZonedDateTime every time I update my model.

**Comment by cbornet** [comment]
If I understand well, you would want to generate `@AuthorizedFeignClient` instead of the regular `@FeignClient`, is that correct ?

**Comment by cbornet** [comment]
As for the DateTime class, it should be replaced by ZonedDateTime during generation. I'll check if there is a bug here.

**Comment by brunnels** [comment]
Correct,  `@AuthorizedFeignClient` instead of the regular `@FeignClient`

Also application-*.yml settings support on the AuthorizedFeignClient parameters.

Also directory structure and file/class naming changes.

**Comment by cbornet** [comment]
OK. I can certainly replace the code with a regexp if option "uaa" is set.
I'm not sure what application-*.yml setting you want to have. Per client or global for uaa ? If it's global for uaa, then it's the main generator responsibility.
As for the directory structure, you mean to not have the ApiClient in api package ? I'm not sure there is a big gain here...

**Comment by cbornet** [comment]
And since I don't have a uaa setup, PR is welcome as I won't be able to really test what I do !
cc @xetys

**Comment by cbornet** [comment]
@brunnels Note that you can already use the generated code with the current version. You just need to write the @AuthorizedFeignClient interface by yourself.

**Comment by cbornet** [comment]
Actually the problem is that when generating, we can't know if it's for micro-service com or for com with an external system so I don't think we can do that.

**Comment by brunnels** [comment]
I reworked the microservice stuff that you had in there today so it get's the gateway from the registry and then pulls all the services from the gateway.  I changed the questions around some too so it asks if you're doing microservices.  Tomorrow I'll extend the swagger-generator to enable setting the service and api file names and also resolve the ZonedDateTime issue.

**Comment by brunnels** [comment]
The DateTime was supposed to be fixed here https://github.com/swagger-api/swagger-codegen/issues/1035 but I'm not able to resolve it with all the combination of --import-mappins, --type-mappings, or --instantiation-types that I've tried.  I checked out the swagger-codegen master and recompiled to ensure I had the latest.  

The maven project isn't loading right in intellij so I have to get that resolved then I should start making some progress.  Once I have debugging going I can track down the problem.

**Comment by brunnels** [comment]
Okay, I figured out the ZonedDateTime.  The following works except it leaves behind an `import java.time.OffsetDateTime;`

Need to have these parameters

```
--type-mappings OffsetDateTime=ZonedDateTime
--instantiation-types OffsetDateTime=java.time.ZonedDateTime
--additional-properties dateLibrary=java8
```

`--import-mappings` didn't seem to do anything.

**Comment by brunnels** [comment]
Okay, finally figured it out.  :smile: 

http://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java#L262-280

Because that looks for `joda` or starts with `java8` you can bypass it all by setting dateLibrary to custom.  So this works and doesn't have extra imports

```
--additional-properties dateLibrary=custom
--type-mappings DateTime=ZonedDateTime
--import-mappings ZonedDateTime=java.time.ZonedDateTime
```

**Comment by cbornet** [comment]
Hacky but nice !

**Comment by cbornet** [comment]
I guess it was working with previous versions of the codegen because the dateLibrary used to be 'legacy' (java.util.Date) so there was no extra imports.

**Comment by brunnels** [comment]
One last thing I would like to do is have the swagger-codegen-cli create the files in a temp location and then use yeoman to move the files to the final location.  Then you would have the standard `Overwrite file.java? (Ynaxdh)`  Not sure the best way to do that so any examples would be appreciated.

**Comment by cbornet** [comment]
Yes, that was on my TODO too.

**Comment by brunnels** [comment]
I got it.  I'll send you a PR soon.

**Comment by brunnels** [comment]
Well, almost.  swagger-codegen-cli line endings aren't normal so when I open the file in intellij it fixes them.  This causes all lines to appear as different when you use the diff functionality pretty much nullifying any benefit.  I'll investigate fixing the line endings before copying.

**Comment by brunnels** [comment]
nevermind, was my fault when editing the templates with notepad2.  It set the line endings to windows.

**Comment by cbornet** [comment]
I've made a fix so that jsr310 dates are used instead of joda.
I didn't change OffsetDateTime to ZonedDateTime because I think OffsetDateTime better represents the swagger date-time object. And actually we should also have supported OffsetDateTime instead of ZonedDateTime in JHipster... I'll probably do OffsetDateTime/Instant/LocalDateTime support once JH4 is out.

**Comment by brunnels** [comment]
I forked and checked in my changes that are working for me.  https://github.com/brunnels/generator-jhipster-swagger-cli/commit/940a48264a020b5794058724be941eda9a5d2411
